// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1tZXNzYWdlLnByb3RvGgxvcGNvZGUucHJvdG8aC2xvZ2luLnByb3RvGgpw",
          "aW5nLnByb3RvGgpiYXNlLnByb3RvGgxjdXN0b20ucHJvdG8aCml0ZW0ucHJv",
          "dG8aCndhdmUucHJvdG8aDmN1cnJlbmN5LnByb3RvIr0CCgtDMlNfTWVzc2Fn",
          "ZRIPCgdzZXNzaW9uGAEgASgEEhsKBWxvZ2luGAIgASgLMgouQzJTX0xvZ2lu",
          "SAASGQoEcGluZxgEIAEoCzIJLkMyU19QaW5nSAASHgoJYmFzZV9kYXRhGAUg",
          "ASgLMgkuQzJTX0Jhc2VIABIiCgtjdXN0b21fZGF0YRgGIAEoCzILLkMyU19D",
          "dXN0b21IABIqCg11cGxvYWRfY3VzdG9tGAcgASgLMhEuQzJTX1VwbG9hZEN1",
          "c3RvbUgAEh4KCWl0ZW1fZGF0YRgIIAEoCzIJLkMyU19JdGVtSAASJgoLd2F2",
          "ZV9yZXN1bHQYCSABKAsyDy5DMlNfV2F2ZVJlc3VsdEgAEiYKDWN1cnJlbmN5",
          "X2RhdGEYCiABKAsyDS5DMlNfQ3VycmVuY3lIAEIFCgNtc2cihgIKC1MyQ19N",
          "ZXNzYWdlEg8KB3Nlc3Npb24YASABKAQSGwoEY29kZRgCIAEoDjILLlMyQ19P",
          "UENvZGVIABIbCgVsb2dpbhgDIAEoCzIKLlMyQ19Mb2dpbkgAEhkKBHBpbmcY",
          "BSABKAsyCS5TMkNfUGluZ0gAEh4KCWJhc2VfZGF0YRgGIAEoCzIJLlMyQ19C",
          "YXNlSAASIgoLY3VzdG9tX2RhdGEYByABKAsyCy5TMkNfQ3VzdG9tSAASHgoJ",
          "aXRlbV9kYXRhGAggASgLMgkuUzJDX0l0ZW1IABImCg1jdXJyZW5jeV9kYXRh",
          "GAkgASgLMg0uUzJDX0N1cnJlbmN5SABCBQoDbXNnYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::OpcodeReflection.Descriptor, global::LoginReflection.Descriptor, global::PingReflection.Descriptor, global::BaseReflection.Descriptor, global::CustomReflection.Descriptor, global::ItemReflection.Descriptor, global::WaveReflection.Descriptor, global::CurrencyReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_Message), global::C2S_Message.Parser, new[]{ "Session", "Login", "Ping", "BaseData", "CustomData", "UploadCustom", "ItemData", "WaveResult", "CurrencyData" }, new[]{ "Msg" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::S2C_Message), global::S2C_Message.Parser, new[]{ "Session", "Code", "Login", "Ping", "BaseData", "CustomData", "ItemData", "CurrencyData" }, new[]{ "Msg" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class C2S_Message : pb::IMessage<C2S_Message>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C2S_Message> _parser = new pb::MessageParser<C2S_Message>(() => new C2S_Message());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C2S_Message> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Message() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Message(C2S_Message other) : this() {
    session_ = other.session_;
    switch (other.MsgCase) {
      case MsgOneofCase.Login:
        Login = other.Login.Clone();
        break;
      case MsgOneofCase.Ping:
        Ping = other.Ping.Clone();
        break;
      case MsgOneofCase.BaseData:
        BaseData = other.BaseData.Clone();
        break;
      case MsgOneofCase.CustomData:
        CustomData = other.CustomData.Clone();
        break;
      case MsgOneofCase.UploadCustom:
        UploadCustom = other.UploadCustom.Clone();
        break;
      case MsgOneofCase.ItemData:
        ItemData = other.ItemData.Clone();
        break;
      case MsgOneofCase.WaveResult:
        WaveResult = other.WaveResult.Clone();
        break;
      case MsgOneofCase.CurrencyData:
        CurrencyData = other.CurrencyData.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_Message Clone() {
    return new C2S_Message(this);
  }

  /// <summary>Field number for the "session" field.</summary>
  public const int SessionFieldNumber = 1;
  private ulong session_;
  /// <summary>
  /// 会话ID,不可为0,且在整个游戏过程中不能重复
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Session {
    get { return session_; }
    set {
      session_ = value;
    }
  }

  /// <summary>Field number for the "login" field.</summary>
  public const int LoginFieldNumber = 2;
  /// <summary>
  /// 请求登陆
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_Login Login {
    get { return msgCase_ == MsgOneofCase.Login ? (global::C2S_Login) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Login;
    }
  }

  /// <summary>Field number for the "ping" field.</summary>
  public const int PingFieldNumber = 4;
  /// <summary>
  /// 发送ping包
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_Ping Ping {
    get { return msgCase_ == MsgOneofCase.Ping ? (global::C2S_Ping) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Ping;
    }
  }

  /// <summary>Field number for the "base_data" field.</summary>
  public const int BaseDataFieldNumber = 5;
  /// <summary>
  /// 请求基础数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_Base BaseData {
    get { return msgCase_ == MsgOneofCase.BaseData ? (global::C2S_Base) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.BaseData;
    }
  }

  /// <summary>Field number for the "custom_data" field.</summary>
  public const int CustomDataFieldNumber = 6;
  /// <summary>
  /// 请求客户端自定义数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_Custom CustomData {
    get { return msgCase_ == MsgOneofCase.CustomData ? (global::C2S_Custom) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.CustomData;
    }
  }

  /// <summary>Field number for the "upload_custom" field.</summary>
  public const int UploadCustomFieldNumber = 7;
  /// <summary>
  /// 上传客户端自定义数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_UploadCustom UploadCustom {
    get { return msgCase_ == MsgOneofCase.UploadCustom ? (global::C2S_UploadCustom) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.UploadCustom;
    }
  }

  /// <summary>Field number for the "item_data" field.</summary>
  public const int ItemDataFieldNumber = 8;
  /// <summary>
  /// 请求物品数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_Item ItemData {
    get { return msgCase_ == MsgOneofCase.ItemData ? (global::C2S_Item) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ItemData;
    }
  }

  /// <summary>Field number for the "wave_result" field.</summary>
  public const int WaveResultFieldNumber = 9;
  /// <summary>
  /// 上传波次结果
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_WaveResult WaveResult {
    get { return msgCase_ == MsgOneofCase.WaveResult ? (global::C2S_WaveResult) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.WaveResult;
    }
  }

  /// <summary>Field number for the "currency_data" field.</summary>
  public const int CurrencyDataFieldNumber = 10;
  /// <summary>
  /// 请求货币数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::C2S_Currency CurrencyData {
    get { return msgCase_ == MsgOneofCase.CurrencyData ? (global::C2S_Currency) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.CurrencyData;
    }
  }

  private object msg_;
  /// <summary>Enum of possible cases for the "msg" oneof.</summary>
  public enum MsgOneofCase {
    None = 0,
    Login = 2,
    Ping = 4,
    BaseData = 5,
    CustomData = 6,
    UploadCustom = 7,
    ItemData = 8,
    WaveResult = 9,
    CurrencyData = 10,
  }
  private MsgOneofCase msgCase_ = MsgOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MsgOneofCase MsgCase {
    get { return msgCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMsg() {
    msgCase_ = MsgOneofCase.None;
    msg_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C2S_Message);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C2S_Message other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Session != other.Session) return false;
    if (!object.Equals(Login, other.Login)) return false;
    if (!object.Equals(Ping, other.Ping)) return false;
    if (!object.Equals(BaseData, other.BaseData)) return false;
    if (!object.Equals(CustomData, other.CustomData)) return false;
    if (!object.Equals(UploadCustom, other.UploadCustom)) return false;
    if (!object.Equals(ItemData, other.ItemData)) return false;
    if (!object.Equals(WaveResult, other.WaveResult)) return false;
    if (!object.Equals(CurrencyData, other.CurrencyData)) return false;
    if (MsgCase != other.MsgCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Session != 0UL) hash ^= Session.GetHashCode();
    if (msgCase_ == MsgOneofCase.Login) hash ^= Login.GetHashCode();
    if (msgCase_ == MsgOneofCase.Ping) hash ^= Ping.GetHashCode();
    if (msgCase_ == MsgOneofCase.BaseData) hash ^= BaseData.GetHashCode();
    if (msgCase_ == MsgOneofCase.CustomData) hash ^= CustomData.GetHashCode();
    if (msgCase_ == MsgOneofCase.UploadCustom) hash ^= UploadCustom.GetHashCode();
    if (msgCase_ == MsgOneofCase.ItemData) hash ^= ItemData.GetHashCode();
    if (msgCase_ == MsgOneofCase.WaveResult) hash ^= WaveResult.GetHashCode();
    if (msgCase_ == MsgOneofCase.CurrencyData) hash ^= CurrencyData.GetHashCode();
    hash ^= (int) msgCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Session != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Session);
    }
    if (msgCase_ == MsgOneofCase.Login) {
      output.WriteRawTag(18);
      output.WriteMessage(Login);
    }
    if (msgCase_ == MsgOneofCase.Ping) {
      output.WriteRawTag(34);
      output.WriteMessage(Ping);
    }
    if (msgCase_ == MsgOneofCase.BaseData) {
      output.WriteRawTag(42);
      output.WriteMessage(BaseData);
    }
    if (msgCase_ == MsgOneofCase.CustomData) {
      output.WriteRawTag(50);
      output.WriteMessage(CustomData);
    }
    if (msgCase_ == MsgOneofCase.UploadCustom) {
      output.WriteRawTag(58);
      output.WriteMessage(UploadCustom);
    }
    if (msgCase_ == MsgOneofCase.ItemData) {
      output.WriteRawTag(66);
      output.WriteMessage(ItemData);
    }
    if (msgCase_ == MsgOneofCase.WaveResult) {
      output.WriteRawTag(74);
      output.WriteMessage(WaveResult);
    }
    if (msgCase_ == MsgOneofCase.CurrencyData) {
      output.WriteRawTag(82);
      output.WriteMessage(CurrencyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Session != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Session);
    }
    if (msgCase_ == MsgOneofCase.Login) {
      output.WriteRawTag(18);
      output.WriteMessage(Login);
    }
    if (msgCase_ == MsgOneofCase.Ping) {
      output.WriteRawTag(34);
      output.WriteMessage(Ping);
    }
    if (msgCase_ == MsgOneofCase.BaseData) {
      output.WriteRawTag(42);
      output.WriteMessage(BaseData);
    }
    if (msgCase_ == MsgOneofCase.CustomData) {
      output.WriteRawTag(50);
      output.WriteMessage(CustomData);
    }
    if (msgCase_ == MsgOneofCase.UploadCustom) {
      output.WriteRawTag(58);
      output.WriteMessage(UploadCustom);
    }
    if (msgCase_ == MsgOneofCase.ItemData) {
      output.WriteRawTag(66);
      output.WriteMessage(ItemData);
    }
    if (msgCase_ == MsgOneofCase.WaveResult) {
      output.WriteRawTag(74);
      output.WriteMessage(WaveResult);
    }
    if (msgCase_ == MsgOneofCase.CurrencyData) {
      output.WriteRawTag(82);
      output.WriteMessage(CurrencyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Session != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Session);
    }
    if (msgCase_ == MsgOneofCase.Login) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Login);
    }
    if (msgCase_ == MsgOneofCase.Ping) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ping);
    }
    if (msgCase_ == MsgOneofCase.BaseData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseData);
    }
    if (msgCase_ == MsgOneofCase.CustomData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomData);
    }
    if (msgCase_ == MsgOneofCase.UploadCustom) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UploadCustom);
    }
    if (msgCase_ == MsgOneofCase.ItemData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemData);
    }
    if (msgCase_ == MsgOneofCase.WaveResult) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(WaveResult);
    }
    if (msgCase_ == MsgOneofCase.CurrencyData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrencyData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C2S_Message other) {
    if (other == null) {
      return;
    }
    if (other.Session != 0UL) {
      Session = other.Session;
    }
    switch (other.MsgCase) {
      case MsgOneofCase.Login:
        if (Login == null) {
          Login = new global::C2S_Login();
        }
        Login.MergeFrom(other.Login);
        break;
      case MsgOneofCase.Ping:
        if (Ping == null) {
          Ping = new global::C2S_Ping();
        }
        Ping.MergeFrom(other.Ping);
        break;
      case MsgOneofCase.BaseData:
        if (BaseData == null) {
          BaseData = new global::C2S_Base();
        }
        BaseData.MergeFrom(other.BaseData);
        break;
      case MsgOneofCase.CustomData:
        if (CustomData == null) {
          CustomData = new global::C2S_Custom();
        }
        CustomData.MergeFrom(other.CustomData);
        break;
      case MsgOneofCase.UploadCustom:
        if (UploadCustom == null) {
          UploadCustom = new global::C2S_UploadCustom();
        }
        UploadCustom.MergeFrom(other.UploadCustom);
        break;
      case MsgOneofCase.ItemData:
        if (ItemData == null) {
          ItemData = new global::C2S_Item();
        }
        ItemData.MergeFrom(other.ItemData);
        break;
      case MsgOneofCase.WaveResult:
        if (WaveResult == null) {
          WaveResult = new global::C2S_WaveResult();
        }
        WaveResult.MergeFrom(other.WaveResult);
        break;
      case MsgOneofCase.CurrencyData:
        if (CurrencyData == null) {
          CurrencyData = new global::C2S_Currency();
        }
        CurrencyData.MergeFrom(other.CurrencyData);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Session = input.ReadUInt64();
          break;
        }
        case 18: {
          global::C2S_Login subBuilder = new global::C2S_Login();
          if (msgCase_ == MsgOneofCase.Login) {
            subBuilder.MergeFrom(Login);
          }
          input.ReadMessage(subBuilder);
          Login = subBuilder;
          break;
        }
        case 34: {
          global::C2S_Ping subBuilder = new global::C2S_Ping();
          if (msgCase_ == MsgOneofCase.Ping) {
            subBuilder.MergeFrom(Ping);
          }
          input.ReadMessage(subBuilder);
          Ping = subBuilder;
          break;
        }
        case 42: {
          global::C2S_Base subBuilder = new global::C2S_Base();
          if (msgCase_ == MsgOneofCase.BaseData) {
            subBuilder.MergeFrom(BaseData);
          }
          input.ReadMessage(subBuilder);
          BaseData = subBuilder;
          break;
        }
        case 50: {
          global::C2S_Custom subBuilder = new global::C2S_Custom();
          if (msgCase_ == MsgOneofCase.CustomData) {
            subBuilder.MergeFrom(CustomData);
          }
          input.ReadMessage(subBuilder);
          CustomData = subBuilder;
          break;
        }
        case 58: {
          global::C2S_UploadCustom subBuilder = new global::C2S_UploadCustom();
          if (msgCase_ == MsgOneofCase.UploadCustom) {
            subBuilder.MergeFrom(UploadCustom);
          }
          input.ReadMessage(subBuilder);
          UploadCustom = subBuilder;
          break;
        }
        case 66: {
          global::C2S_Item subBuilder = new global::C2S_Item();
          if (msgCase_ == MsgOneofCase.ItemData) {
            subBuilder.MergeFrom(ItemData);
          }
          input.ReadMessage(subBuilder);
          ItemData = subBuilder;
          break;
        }
        case 74: {
          global::C2S_WaveResult subBuilder = new global::C2S_WaveResult();
          if (msgCase_ == MsgOneofCase.WaveResult) {
            subBuilder.MergeFrom(WaveResult);
          }
          input.ReadMessage(subBuilder);
          WaveResult = subBuilder;
          break;
        }
        case 82: {
          global::C2S_Currency subBuilder = new global::C2S_Currency();
          if (msgCase_ == MsgOneofCase.CurrencyData) {
            subBuilder.MergeFrom(CurrencyData);
          }
          input.ReadMessage(subBuilder);
          CurrencyData = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Session = input.ReadUInt64();
          break;
        }
        case 18: {
          global::C2S_Login subBuilder = new global::C2S_Login();
          if (msgCase_ == MsgOneofCase.Login) {
            subBuilder.MergeFrom(Login);
          }
          input.ReadMessage(subBuilder);
          Login = subBuilder;
          break;
        }
        case 34: {
          global::C2S_Ping subBuilder = new global::C2S_Ping();
          if (msgCase_ == MsgOneofCase.Ping) {
            subBuilder.MergeFrom(Ping);
          }
          input.ReadMessage(subBuilder);
          Ping = subBuilder;
          break;
        }
        case 42: {
          global::C2S_Base subBuilder = new global::C2S_Base();
          if (msgCase_ == MsgOneofCase.BaseData) {
            subBuilder.MergeFrom(BaseData);
          }
          input.ReadMessage(subBuilder);
          BaseData = subBuilder;
          break;
        }
        case 50: {
          global::C2S_Custom subBuilder = new global::C2S_Custom();
          if (msgCase_ == MsgOneofCase.CustomData) {
            subBuilder.MergeFrom(CustomData);
          }
          input.ReadMessage(subBuilder);
          CustomData = subBuilder;
          break;
        }
        case 58: {
          global::C2S_UploadCustom subBuilder = new global::C2S_UploadCustom();
          if (msgCase_ == MsgOneofCase.UploadCustom) {
            subBuilder.MergeFrom(UploadCustom);
          }
          input.ReadMessage(subBuilder);
          UploadCustom = subBuilder;
          break;
        }
        case 66: {
          global::C2S_Item subBuilder = new global::C2S_Item();
          if (msgCase_ == MsgOneofCase.ItemData) {
            subBuilder.MergeFrom(ItemData);
          }
          input.ReadMessage(subBuilder);
          ItemData = subBuilder;
          break;
        }
        case 74: {
          global::C2S_WaveResult subBuilder = new global::C2S_WaveResult();
          if (msgCase_ == MsgOneofCase.WaveResult) {
            subBuilder.MergeFrom(WaveResult);
          }
          input.ReadMessage(subBuilder);
          WaveResult = subBuilder;
          break;
        }
        case 82: {
          global::C2S_Currency subBuilder = new global::C2S_Currency();
          if (msgCase_ == MsgOneofCase.CurrencyData) {
            subBuilder.MergeFrom(CurrencyData);
          }
          input.ReadMessage(subBuilder);
          CurrencyData = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class S2C_Message : pb::IMessage<S2C_Message>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<S2C_Message> _parser = new pb::MessageParser<S2C_Message>(() => new S2C_Message());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<S2C_Message> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Message() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Message(S2C_Message other) : this() {
    session_ = other.session_;
    switch (other.MsgCase) {
      case MsgOneofCase.Code:
        Code = other.Code;
        break;
      case MsgOneofCase.Login:
        Login = other.Login.Clone();
        break;
      case MsgOneofCase.Ping:
        Ping = other.Ping.Clone();
        break;
      case MsgOneofCase.BaseData:
        BaseData = other.BaseData.Clone();
        break;
      case MsgOneofCase.CustomData:
        CustomData = other.CustomData.Clone();
        break;
      case MsgOneofCase.ItemData:
        ItemData = other.ItemData.Clone();
        break;
      case MsgOneofCase.CurrencyData:
        CurrencyData = other.CurrencyData.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public S2C_Message Clone() {
    return new S2C_Message(this);
  }

  /// <summary>Field number for the "session" field.</summary>
  public const int SessionFieldNumber = 1;
  private ulong session_;
  /// <summary>
  /// 透传 session
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Session {
    get { return session_; }
    set {
      session_ = value;
    }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 2;
  /// <summary>
  /// 通用操作码
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_OPCode Code {
    get { return msgCase_ == MsgOneofCase.Code ? (global::S2C_OPCode) msg_ : global::S2C_OPCode.OpSuccess; }
    set {
      msg_ = value;
      msgCase_ = MsgOneofCase.Code;
    }
  }

  /// <summary>Field number for the "login" field.</summary>
  public const int LoginFieldNumber = 3;
  /// <summary>
  /// 登陆消息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_Login Login {
    get { return msgCase_ == MsgOneofCase.Login ? (global::S2C_Login) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Login;
    }
  }

  /// <summary>Field number for the "ping" field.</summary>
  public const int PingFieldNumber = 5;
  /// <summary>
  /// ping消息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_Ping Ping {
    get { return msgCase_ == MsgOneofCase.Ping ? (global::S2C_Ping) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.Ping;
    }
  }

  /// <summary>Field number for the "base_data" field.</summary>
  public const int BaseDataFieldNumber = 6;
  /// <summary>
  /// 基础数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_Base BaseData {
    get { return msgCase_ == MsgOneofCase.BaseData ? (global::S2C_Base) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.BaseData;
    }
  }

  /// <summary>Field number for the "custom_data" field.</summary>
  public const int CustomDataFieldNumber = 7;
  /// <summary>
  /// 客户端自定义数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_Custom CustomData {
    get { return msgCase_ == MsgOneofCase.CustomData ? (global::S2C_Custom) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.CustomData;
    }
  }

  /// <summary>Field number for the "item_data" field.</summary>
  public const int ItemDataFieldNumber = 8;
  /// <summary>
  /// 物品数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_Item ItemData {
    get { return msgCase_ == MsgOneofCase.ItemData ? (global::S2C_Item) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ItemData;
    }
  }

  /// <summary>Field number for the "currency_data" field.</summary>
  public const int CurrencyDataFieldNumber = 9;
  /// <summary>
  /// 货币数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::S2C_Currency CurrencyData {
    get { return msgCase_ == MsgOneofCase.CurrencyData ? (global::S2C_Currency) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.CurrencyData;
    }
  }

  private object msg_;
  /// <summary>Enum of possible cases for the "msg" oneof.</summary>
  public enum MsgOneofCase {
    None = 0,
    Code = 2,
    Login = 3,
    Ping = 5,
    BaseData = 6,
    CustomData = 7,
    ItemData = 8,
    CurrencyData = 9,
  }
  private MsgOneofCase msgCase_ = MsgOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MsgOneofCase MsgCase {
    get { return msgCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMsg() {
    msgCase_ = MsgOneofCase.None;
    msg_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as S2C_Message);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(S2C_Message other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Session != other.Session) return false;
    if (Code != other.Code) return false;
    if (!object.Equals(Login, other.Login)) return false;
    if (!object.Equals(Ping, other.Ping)) return false;
    if (!object.Equals(BaseData, other.BaseData)) return false;
    if (!object.Equals(CustomData, other.CustomData)) return false;
    if (!object.Equals(ItemData, other.ItemData)) return false;
    if (!object.Equals(CurrencyData, other.CurrencyData)) return false;
    if (MsgCase != other.MsgCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Session != 0UL) hash ^= Session.GetHashCode();
    if (msgCase_ == MsgOneofCase.Code) hash ^= Code.GetHashCode();
    if (msgCase_ == MsgOneofCase.Login) hash ^= Login.GetHashCode();
    if (msgCase_ == MsgOneofCase.Ping) hash ^= Ping.GetHashCode();
    if (msgCase_ == MsgOneofCase.BaseData) hash ^= BaseData.GetHashCode();
    if (msgCase_ == MsgOneofCase.CustomData) hash ^= CustomData.GetHashCode();
    if (msgCase_ == MsgOneofCase.ItemData) hash ^= ItemData.GetHashCode();
    if (msgCase_ == MsgOneofCase.CurrencyData) hash ^= CurrencyData.GetHashCode();
    hash ^= (int) msgCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Session != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Session);
    }
    if (msgCase_ == MsgOneofCase.Code) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Code);
    }
    if (msgCase_ == MsgOneofCase.Login) {
      output.WriteRawTag(26);
      output.WriteMessage(Login);
    }
    if (msgCase_ == MsgOneofCase.Ping) {
      output.WriteRawTag(42);
      output.WriteMessage(Ping);
    }
    if (msgCase_ == MsgOneofCase.BaseData) {
      output.WriteRawTag(50);
      output.WriteMessage(BaseData);
    }
    if (msgCase_ == MsgOneofCase.CustomData) {
      output.WriteRawTag(58);
      output.WriteMessage(CustomData);
    }
    if (msgCase_ == MsgOneofCase.ItemData) {
      output.WriteRawTag(66);
      output.WriteMessage(ItemData);
    }
    if (msgCase_ == MsgOneofCase.CurrencyData) {
      output.WriteRawTag(74);
      output.WriteMessage(CurrencyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Session != 0UL) {
      output.WriteRawTag(8);
      output.WriteUInt64(Session);
    }
    if (msgCase_ == MsgOneofCase.Code) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Code);
    }
    if (msgCase_ == MsgOneofCase.Login) {
      output.WriteRawTag(26);
      output.WriteMessage(Login);
    }
    if (msgCase_ == MsgOneofCase.Ping) {
      output.WriteRawTag(42);
      output.WriteMessage(Ping);
    }
    if (msgCase_ == MsgOneofCase.BaseData) {
      output.WriteRawTag(50);
      output.WriteMessage(BaseData);
    }
    if (msgCase_ == MsgOneofCase.CustomData) {
      output.WriteRawTag(58);
      output.WriteMessage(CustomData);
    }
    if (msgCase_ == MsgOneofCase.ItemData) {
      output.WriteRawTag(66);
      output.WriteMessage(ItemData);
    }
    if (msgCase_ == MsgOneofCase.CurrencyData) {
      output.WriteRawTag(74);
      output.WriteMessage(CurrencyData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Session != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Session);
    }
    if (msgCase_ == MsgOneofCase.Code) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
    }
    if (msgCase_ == MsgOneofCase.Login) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Login);
    }
    if (msgCase_ == MsgOneofCase.Ping) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ping);
    }
    if (msgCase_ == MsgOneofCase.BaseData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseData);
    }
    if (msgCase_ == MsgOneofCase.CustomData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CustomData);
    }
    if (msgCase_ == MsgOneofCase.ItemData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemData);
    }
    if (msgCase_ == MsgOneofCase.CurrencyData) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrencyData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(S2C_Message other) {
    if (other == null) {
      return;
    }
    if (other.Session != 0UL) {
      Session = other.Session;
    }
    switch (other.MsgCase) {
      case MsgOneofCase.Code:
        Code = other.Code;
        break;
      case MsgOneofCase.Login:
        if (Login == null) {
          Login = new global::S2C_Login();
        }
        Login.MergeFrom(other.Login);
        break;
      case MsgOneofCase.Ping:
        if (Ping == null) {
          Ping = new global::S2C_Ping();
        }
        Ping.MergeFrom(other.Ping);
        break;
      case MsgOneofCase.BaseData:
        if (BaseData == null) {
          BaseData = new global::S2C_Base();
        }
        BaseData.MergeFrom(other.BaseData);
        break;
      case MsgOneofCase.CustomData:
        if (CustomData == null) {
          CustomData = new global::S2C_Custom();
        }
        CustomData.MergeFrom(other.CustomData);
        break;
      case MsgOneofCase.ItemData:
        if (ItemData == null) {
          ItemData = new global::S2C_Item();
        }
        ItemData.MergeFrom(other.ItemData);
        break;
      case MsgOneofCase.CurrencyData:
        if (CurrencyData == null) {
          CurrencyData = new global::S2C_Currency();
        }
        CurrencyData.MergeFrom(other.CurrencyData);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Session = input.ReadUInt64();
          break;
        }
        case 16: {
          msg_ = input.ReadEnum();
          msgCase_ = MsgOneofCase.Code;
          break;
        }
        case 26: {
          global::S2C_Login subBuilder = new global::S2C_Login();
          if (msgCase_ == MsgOneofCase.Login) {
            subBuilder.MergeFrom(Login);
          }
          input.ReadMessage(subBuilder);
          Login = subBuilder;
          break;
        }
        case 42: {
          global::S2C_Ping subBuilder = new global::S2C_Ping();
          if (msgCase_ == MsgOneofCase.Ping) {
            subBuilder.MergeFrom(Ping);
          }
          input.ReadMessage(subBuilder);
          Ping = subBuilder;
          break;
        }
        case 50: {
          global::S2C_Base subBuilder = new global::S2C_Base();
          if (msgCase_ == MsgOneofCase.BaseData) {
            subBuilder.MergeFrom(BaseData);
          }
          input.ReadMessage(subBuilder);
          BaseData = subBuilder;
          break;
        }
        case 58: {
          global::S2C_Custom subBuilder = new global::S2C_Custom();
          if (msgCase_ == MsgOneofCase.CustomData) {
            subBuilder.MergeFrom(CustomData);
          }
          input.ReadMessage(subBuilder);
          CustomData = subBuilder;
          break;
        }
        case 66: {
          global::S2C_Item subBuilder = new global::S2C_Item();
          if (msgCase_ == MsgOneofCase.ItemData) {
            subBuilder.MergeFrom(ItemData);
          }
          input.ReadMessage(subBuilder);
          ItemData = subBuilder;
          break;
        }
        case 74: {
          global::S2C_Currency subBuilder = new global::S2C_Currency();
          if (msgCase_ == MsgOneofCase.CurrencyData) {
            subBuilder.MergeFrom(CurrencyData);
          }
          input.ReadMessage(subBuilder);
          CurrencyData = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Session = input.ReadUInt64();
          break;
        }
        case 16: {
          msg_ = input.ReadEnum();
          msgCase_ = MsgOneofCase.Code;
          break;
        }
        case 26: {
          global::S2C_Login subBuilder = new global::S2C_Login();
          if (msgCase_ == MsgOneofCase.Login) {
            subBuilder.MergeFrom(Login);
          }
          input.ReadMessage(subBuilder);
          Login = subBuilder;
          break;
        }
        case 42: {
          global::S2C_Ping subBuilder = new global::S2C_Ping();
          if (msgCase_ == MsgOneofCase.Ping) {
            subBuilder.MergeFrom(Ping);
          }
          input.ReadMessage(subBuilder);
          Ping = subBuilder;
          break;
        }
        case 50: {
          global::S2C_Base subBuilder = new global::S2C_Base();
          if (msgCase_ == MsgOneofCase.BaseData) {
            subBuilder.MergeFrom(BaseData);
          }
          input.ReadMessage(subBuilder);
          BaseData = subBuilder;
          break;
        }
        case 58: {
          global::S2C_Custom subBuilder = new global::S2C_Custom();
          if (msgCase_ == MsgOneofCase.CustomData) {
            subBuilder.MergeFrom(CustomData);
          }
          input.ReadMessage(subBuilder);
          CustomData = subBuilder;
          break;
        }
        case 66: {
          global::S2C_Item subBuilder = new global::S2C_Item();
          if (msgCase_ == MsgOneofCase.ItemData) {
            subBuilder.MergeFrom(ItemData);
          }
          input.ReadMessage(subBuilder);
          ItemData = subBuilder;
          break;
        }
        case 74: {
          global::S2C_Currency subBuilder = new global::S2C_Currency();
          if (msgCase_ == MsgOneofCase.CurrencyData) {
            subBuilder.MergeFrom(CurrencyData);
          }
          input.ReadMessage(subBuilder);
          CurrencyData = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
