// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: opcode.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from opcode.proto</summary>
public static partial class OpcodeReflection {

  #region Descriptor
  /// <summary>File descriptor for opcode.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OpcodeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxvcGNvZGUucHJvdG8quQIKClMyQ19PUENvZGUSDgoKT1BfU3VjY2VzcxAA",
          "Eg0KCU9QX0ZhaWxlZBABEhYKEk9QX1Nlc3Npb25fRXhwaXJlZBACEhwKGE9Q",
          "X1Nlc3Npb25fVG9rZW5fSW52YWxpZBADEhUKEU9QXzNrcF9Ob3RfRW5vdWdo",
          "EGUSGQoVT1BfU3RhbWluYV9Ob3RfRW5vdWdoEGYSFgoST1BfSXRlbV9Ob3Rf",
          "RW5vdWdoEGcSHQoYT1BfTG9naW5fSW52YWxpZF9BY2NvdW50EOkHEhkKFE9Q",
          "X0xvZ2luX0F1dGhfZmFpbGVkEOoHEhoKFU9QX0xvZ291dF9PdGhlcl9Mb2dp",
          "bhDNCBIWChFPUF9Mb2dvdXRfVGltZW91dBDOCBIeChlPUF9Mb2dvdXRfU2Vy",
          "dmVyX1NodXRkb3duEM8IYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::S2C_OPCode), }, null, null));
  }
  #endregion

}
#region Enums
public enum S2C_OPCode {
  /// <summary>
  /// 操作成功
  /// </summary>
  [pbr::OriginalName("OP_Success")] OpSuccess = 0,
  /// <summary>
  /// 操作失败
  /// </summary>
  [pbr::OriginalName("OP_Failed")] OpFailed = 1,
  /// <summary>
  /// 会话过期,需重新登陆
  /// </summary>
  [pbr::OriginalName("OP_Session_Expired")] OpSessionExpired = 2,
  /// <summary>
  /// 会话令牌无效
  /// </summary>
  [pbr::OriginalName("OP_Session_Token_Invalid")] OpSessionTokenInvalid = 3,
  /// <summary>
  /// 金币不足
  /// </summary>
  [pbr::OriginalName("OP_3kp_Not_Enough")] Op3KpNotEnough = 101,
  /// <summary>
  /// 体力不足
  /// </summary>
  [pbr::OriginalName("OP_Stamina_Not_Enough")] OpStaminaNotEnough = 102,
  /// <summary>
  /// 物品不足
  /// </summary>
  [pbr::OriginalName("OP_Item_Not_Enough")] OpItemNotEnough = 103,
  /// <summary>
  /// 无效账号(手机号方式)
  /// </summary>
  [pbr::OriginalName("OP_Login_Invalid_Account")] OpLoginInvalidAccount = 1001,
  /// <summary>
  /// 平台认证失败
  /// </summary>
  [pbr::OriginalName("OP_Login_Auth_failed")] OpLoginAuthFailed = 1002,
  /// <summary>
  /// 顶号
  /// </summary>
  [pbr::OriginalName("OP_Logout_Other_Login")] OpLogoutOtherLogin = 1101,
  /// <summary>
  /// 心跳超时
  /// </summary>
  [pbr::OriginalName("OP_Logout_Timeout")] OpLogoutTimeout = 1102,
  /// <summary>
  /// 服务器关闭
  /// </summary>
  [pbr::OriginalName("OP_Logout_Server_Shutdown")] OpLogoutServerShutdown = 1103,
}

#endregion


#endregion Designer generated code
