// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wave.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from wave.proto</summary>
public static partial class WaveReflection {

  #region Descriptor
  /// <summary>File descriptor for wave.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WaveReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgp3YXZlLnByb3RvIkEKDkMyU19XYXZlUmVzdWx0Eg8KB3dhdmVfaWQYASAB",
          "KA0SDQoFcG9pbnQYAiABKAQSDwoHdGhyZWVrcBgDIAEoBGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::C2S_WaveResult), global::C2S_WaveResult.Parser, new[]{ "WaveId", "Point", "Threekp" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class C2S_WaveResult : pb::IMessage<C2S_WaveResult>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<C2S_WaveResult> _parser = new pb::MessageParser<C2S_WaveResult>(() => new C2S_WaveResult());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<C2S_WaveResult> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WaveReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_WaveResult() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_WaveResult(C2S_WaveResult other) : this() {
    waveId_ = other.waveId_;
    point_ = other.point_;
    threekp_ = other.threekp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public C2S_WaveResult Clone() {
    return new C2S_WaveResult(this);
  }

  /// <summary>Field number for the "wave_id" field.</summary>
  public const int WaveIdFieldNumber = 1;
  private uint waveId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint WaveId {
    get { return waveId_; }
    set {
      waveId_ = value;
    }
  }

  /// <summary>Field number for the "point" field.</summary>
  public const int PointFieldNumber = 2;
  private ulong point_;
  /// <summary>
  ///获得积分
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Point {
    get { return point_; }
    set {
      point_ = value;
    }
  }

  /// <summary>Field number for the "threekp" field.</summary>
  public const int ThreekpFieldNumber = 3;
  private ulong threekp_;
  /// <summary>
  ///获得3kp数量
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Threekp {
    get { return threekp_; }
    set {
      threekp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as C2S_WaveResult);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(C2S_WaveResult other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (WaveId != other.WaveId) return false;
    if (Point != other.Point) return false;
    if (Threekp != other.Threekp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (WaveId != 0) hash ^= WaveId.GetHashCode();
    if (Point != 0UL) hash ^= Point.GetHashCode();
    if (Threekp != 0UL) hash ^= Threekp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (WaveId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(WaveId);
    }
    if (Point != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Point);
    }
    if (Threekp != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(Threekp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (WaveId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(WaveId);
    }
    if (Point != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Point);
    }
    if (Threekp != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(Threekp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (WaveId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WaveId);
    }
    if (Point != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Point);
    }
    if (Threekp != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Threekp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(C2S_WaveResult other) {
    if (other == null) {
      return;
    }
    if (other.WaveId != 0) {
      WaveId = other.WaveId;
    }
    if (other.Point != 0UL) {
      Point = other.Point;
    }
    if (other.Threekp != 0UL) {
      Threekp = other.Threekp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          WaveId = input.ReadUInt32();
          break;
        }
        case 16: {
          Point = input.ReadUInt64();
          break;
        }
        case 24: {
          Threekp = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          WaveId = input.ReadUInt32();
          break;
        }
        case 16: {
          Point = input.ReadUInt64();
          break;
        }
        case 24: {
          Threekp = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
